<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="btn-group mr-2">
        <a class="btn btn-primary" href="<?= $this->url('Insurance:Admin:Issuer@addAction'); ?>"><?php $this->show('Add new issuer'); ?></a>
    </div>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', ['caption' => 'Issuers']); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($issuers, [
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'phone'
                    ],

                    [
                        'column' => 'email'
                    ]
                ],

                'actions' => [
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Insurance:Admin:Issuer@editAction', $row['id']),
                            $this->translate('Edit this issuer')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Insurance:Admin:Issuer@deleteAction', $row['id']),
                            $this->translate('Remove this issuer')
                        );
                    }
                ]
            ])); ?>

            <?php if (empty($issuers)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="fas fa-info-circle fa-2x"></i> <?php $this->show('No issuers'); ?></h2>
            </div>
            <?php endif; ?>

        </div>
    </form>
</div>
